# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://powershellexplained.com"
baseurl: ""
excerpt_separator: <!--more-->

# If you are building a GitHub project page then use these settings:
#url: "https://kevinmarquette.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: PowerShell Explained with Kevin Marquette

# Short description of your site
description: I love to explore and discover how Powershell works.

#avatarurl: "https://www.gravatar.com/avatar/d7d29e9573b5da44d9886df24fcc6142" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme/?utm_source=blog&utm_medium=blog&utm_content=navbar"
  Search: "search/?utm_source=blog&utm_medium=blog&utm_content=navbar"
  Resources:
    - Blog: "blog/?utm_source=blog&utm_medium=blog&utm_content=navbar"
    - Tags: "tags/?utm_source=blog&utm_medium=blog&utm_content=navbar"
    - SiteMap: "sitemap/?utm_source=blog&utm_medium=blog&utm_content=navbar"
    - MSSQL Server: "sql/?utm_source=blog&utm_medium=blog&utm_content=navbar"
    - GitHub Pages: "https://pages.github.com/"
  Home: "?utm_source=blog&utm_medium=blog&utm_content=navbar"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Kevin Marquette
  email: "kevmar@gmail.com"
  github: kevinmarquette    # eg. daattali
  twitter: kevinmarquette   # eg. daattali
  linkedin: kevinmarquette  # eg. daattali
  stackoverflow: kevmar  # eg. "3943160/daattali"
  youtube: kevinmarquete # eg. user/daattali or channel/daattali

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: false
  twitter: true
  github: true
  linkedin: true
  xing: false
  stackoverflow: false
  instagram: false
  youtube: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "kevinmarquette.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-85734886-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 15
paginate_path: /blog/page:num/

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate

plugins:
  - jekyll-redirect-from
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
